# These are supported funding model platforms

github: # MJ-AHMAD
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # mjahmad
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://yourwebsite.com/fund/project_1', 'https://yourwebsite.com/fund/project_2', 'https://yourwebsite.com/fund/project_3']